name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version
        id: version
        run: |
          # Get the number of commits since the beginning
          BUILD_NUMBER=$(git rev-list --count HEAD)
          VERSION="v1.0.${BUILD_NUMBER}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware

      - name: Create archive
        run: |
          cd firmware
          zip -r ../zmk-firmware-${{ steps.version.outputs.version }}.zip .

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: ZMK Firmware ${{ steps.version.outputs.version }}
          body: |
            Automated firmware build from commit ${{ github.sha }}
            
            This release contains the latest ZMK firmware built from the main branch.
            
            **Changes in this build:**
            - Built from commit: ${{ github.sha }}
            - Build number: ${{ steps.version.outputs.version }}
          files: zmk-firmware-${{ steps.version.outputs.version }}.zip
          draft: false
          prerelease: false
